get_directory_property(progs BUILDSYSTEM_TARGETS)

FOREACH(prog ${progs})
  get_target_property(property_var "${prog}" TYPE)
  if(NOT property_var STREQUAL EXECUTABLE)
    continue()
  endif()
  TARGET_LINK_LIBRARIES(${prog} PRIVATE OpenGLCPP)

  ADD_CUSTOM_COMMAND(TARGET ${prog} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_directory ${CMAKE_CURRENT_LIST_DIR}/../resource ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CFG_INTDIR}/resource)
  SET(shader_dir ${CMAKE_CURRENT_SOURCE_DIR}/shader)
  IF(EXISTS ${shader_dir})
    ADD_CUSTOM_COMMAND(TARGET ${prog} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_directory ${shader_dir} ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CFG_INTDIR}/shader)
  ENDIF()
ENDFOREACH()
